---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
        - name: server
          image: itzg/minecraft-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "true"
            - name: VERSION
              value: "1.16.5"
            - name: ONLINE_MODE # https://github.com/itzg/docker-minecraft-server#online-mode
              value: "FALSE"
          resources: # https://minecraft.fandom.com/wiki/Java_Edition#System_requirements
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "4000m"
          ports:
            - containerPort: 25565
              name: minecraft
          startupProbe:
            tcpSocket:
              port: minecraft
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: minecraft
            periodSeconds: 10
            failureThreshold: 1
          livenessProbe:
            tcpSocket:
              port: minecraft
            periodSeconds: 10
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
  selector:
    app: minecraft-server
